version: '2'

services:
  ldap_service:
    image: osixia/openldap:1.1.10
    container_name: ldap-service
    environment:
     - LDAP_ORGANISATION="osixia.net" 
     - LDAP_DOMAIN="osixia.net"
     - LDAP_HOST="unice.fr"
     - TZ=Europe/Paris # meme si ce n'est pas utilise par le service, c'est toujours interessant de le preciser
    volumes:
    - db_data:/var/lib/ldap
    - db_config:/etc/ldap
  
    network_mode: host
#    restart: unless-stopped
    restart: always
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.2
    container_name: phpldapadmin_service
    restart: always
    volumes:
    - db_content:/var/www/phpldapadmin
#    environment:
#      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - "6443:443"
      - "6080:80"
    network_mode: bridge  
# declarations des volumes utilises par les services (multi-conteneurs)
volumes:
    db_data:
    db_config:
    db_content:

 
